# Generated by Django 2.2.7 on 2019-12-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major_info',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('info', models.TextField()),
                ('established', models.TextField()),
            ],
        ),
    ]
