# Generated by Django 2.2.6 on 2019-12-02 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MajorInfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='major_info',
            old_name='id',
            new_name='MajorName',
        ),
    ]
