# Generated by Django 2.2.6 on 2019-12-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College_info',
            fields=[
                ('college_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('info', models.TextField()),
                ('established', models.TextField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
